# Generated by Django 4.0.2 on 2022-02-26 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('tickerID', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=6)),
                ('companyName', models.CharField(blank=True, max_length=155, unique=True)),
            ],
            options={
                'db_table': 'Ticker',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('commentID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('timeCreated', models.DateTimeField()),
                ('postbody', models.TextField(max_length=2000)),
                ('parentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redditApp.submission')),
                ('tickerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='redditApp.ticker')),
            ],
            options={
                'db_table': 'Submission',
            },
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('sentimentID', models.AutoField(primary_key=True, serialize=False)),
                ('sentimentScore', models.DecimalField(decimal_places=4, max_digits=6)),
                ('commentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redditApp.submission')),
                ('tickerID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='redditApp.ticker')),
            ],
            options={
                'db_table': 'Sentiment',
            },
        ),
    ]
